//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18034
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Informer.Resources.Views {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Craft {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Craft() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Informer.Resources.Views.Craft", typeof(Craft).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Шанс 100%.
        /// </summary>
        public static string chance_100 {
            get {
                return ResourceManager.GetString("chance_100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Шанс 60%.
        /// </summary>
        public static string chance_60 {
            get {
                return ResourceManager.GetString("chance_60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Шанс 70%.
        /// </summary>
        public static string chance_70 {
            get {
                return ResourceManager.GetString("chance_70", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка! Крафт по рецепту не найден.
        /// </summary>
        public static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Состав.
        /// </summary>
        public static string fds_consist {
            get {
                return ResourceManager.GetString("fds_consist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Параметры поиска.
        /// </summary>
        public static string fds_param {
            get {
                return ResourceManager.GetString("fds_param", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Рецепты.
        /// </summary>
        public static string fds_rec {
            get {
                return ResourceManager.GetString("fds_rec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Что могло бы получиться.
        /// </summary>
        public static string fds_that {
            get {
                return ResourceManager.GetString("fds_that", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1 уровень крафта.
        /// </summary>
        public static string lvl_1 {
            get {
                return ResourceManager.GetString("lvl_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 10 уровень крафта.
        /// </summary>
        public static string lvl_10 {
            get {
                return ResourceManager.GetString("lvl_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 2 уровень крафта.
        /// </summary>
        public static string lvl_2 {
            get {
                return ResourceManager.GetString("lvl_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 3 уровень крафта.
        /// </summary>
        public static string lvl_3 {
            get {
                return ResourceManager.GetString("lvl_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 4 уровень крафта.
        /// </summary>
        public static string lvl_4 {
            get {
                return ResourceManager.GetString("lvl_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 5 уровень крафта.
        /// </summary>
        public static string lvl_5 {
            get {
                return ResourceManager.GetString("lvl_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 6 уровень крафта.
        /// </summary>
        public static string lvl_6 {
            get {
                return ResourceManager.GetString("lvl_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 7 уровень крафта.
        /// </summary>
        public static string lvl_7 {
            get {
                return ResourceManager.GetString("lvl_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 8 уровень крафта.
        /// </summary>
        public static string lvl_8 {
            get {
                return ResourceManager.GetString("lvl_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 9 уровень крафта.
        /// </summary>
        public static string lvl_9 {
            get {
                return ResourceManager.GetString("lvl_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Все.
        /// </summary>
        public static string tip_all {
            get {
                return ResourceManager.GetString("tip_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Броня.
        /// </summary>
        public static string tip_armor {
            get {
                return ResourceManager.GetString("tip_armor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Материалы.
        /// </summary>
        public static string tip_etc {
            get {
                return ResourceManager.GetString("tip_etc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Оружие.
        /// </summary>
        public static string tip_weapon {
            get {
                return ResourceManager.GetString("tip_weapon", resourceCulture);
            }
        }
    }
}
