//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18052
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Informer.Resources.Views {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Item {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Item() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Informer.Resources.Views.Item", typeof(Item).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Характеристики предмета.
        /// </summary>
        public static string detail_character {
            get {
                return ResourceManager.GetString("detail_character", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кристаллов:.
        /// </summary>
        public static string detail_cri_count {
            get {
                return ResourceManager.GetString("detail_cri_count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Маг. Атака:.
        /// </summary>
        public static string detail_m_atk {
            get {
                return ResourceManager.GetString("detail_m_atk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Маг. Защита:.
        /// </summary>
        public static string detail_m_def {
            get {
                return ResourceManager.GetString("detail_m_def", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Физ. Атака:.
        /// </summary>
        public static string detail_p_atk {
            get {
                return ResourceManager.GetString("detail_p_atk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Физ. Защита:.
        /// </summary>
        public static string detail_p_def {
            get {
                return ResourceManager.GetString("detail_p_def", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Исп. Заряд Души:.
        /// </summary>
        public static string detail_soul_shut {
            get {
                return ResourceManager.GetString("detail_soul_shut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Скорость Атаки:.
        /// </summary>
        public static string detail_spid_atk {
            get {
                return ResourceManager.GetString("detail_spid_atk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Исп. Заряд Духа:.
        /// </summary>
        public static string detail_spirit_shut {
            get {
                return ResourceManager.GetString("detail_spirit_shut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка! Итем не найден.
        /// </summary>
        public static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дроп.
        /// </summary>
        public static string fd_drop {
            get {
                return ResourceManager.GetString("fd_drop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Список итемов.
        /// </summary>
        public static string fd_item_list {
            get {
                return ResourceManager.GetString("fd_item_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Итемы.
        /// </summary>
        public static string fd_items {
            get {
                return ResourceManager.GetString("fd_items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Споил.
        /// </summary>
        public static string fd_spoil {
            get {
                return ResourceManager.GetString("fd_spoil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Квесты где встречается item.
        /// </summary>
        public static string fds_quest {
            get {
                return ResourceManager.GetString("fds_quest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на тяжелый,лёгкий,магический.
        /// </summary>
        public static string item_tip {
            get {
                return ResourceManager.GetString("item_tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Книги.
        /// </summary>
        public static string menu_book {
            get {
                return ResourceManager.GetString("menu_book", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Наём.
        /// </summary>
        public static string menu_mercenaru {
            get {
                return ResourceManager.GetString("menu_mercenaru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Деньги.
        /// </summary>
        public static string menu_money {
            get {
                return ResourceManager.GetString("menu_money", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Питомцы.
        /// </summary>
        public static string menu_pet {
            get {
                return ResourceManager.GetString("menu_pet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Зелья.
        /// </summary>
        public static string menu_potion {
            get {
                return ResourceManager.GetString("menu_potion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Квест.
        /// </summary>
        public static string menu_quest {
            get {
                return ResourceManager.GetString("menu_quest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ресурсы.
        /// </summary>
        public static string menu_resi {
            get {
                return ResourceManager.GetString("menu_resi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Руны.
        /// </summary>
        public static string menu_runa {
            get {
                return ResourceManager.GetString("menu_runa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Свитки.
        /// </summary>
        public static string menu_scroll {
            get {
                return ResourceManager.GetString("menu_scroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Соски.
        /// </summary>
        public static string menu_ss {
            get {
                return ResourceManager.GetString("menu_ss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Цена продажи:.
        /// </summary>
        public static string price {
            get {
                return ResourceManager.GetString("price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите название итема для поиска (русское или английское)..
        /// </summary>
        public static string search_span {
            get {
                return ResourceManager.GetString("search_span", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Крафт.
        /// </summary>
        public static string show_craft {
            get {
                return ResourceManager.GetString("show_craft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вес:.
        /// </summary>
        public static string weight {
            get {
                return ResourceManager.GetString("weight", resourceCulture);
            }
        }
    }
}
