//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18052
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Informer.Resources.Views {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Npc {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Npc() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Informer.Resources.Views.Npc", typeof(Npc).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Все.
        /// </summary>
        public static string all {
            get {
                return ResourceManager.GetString("all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Скрыть.
        /// </summary>
        public static string button_hiden {
            get {
                return ResourceManager.GetString("button_hiden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на X.
        /// </summary>
        public static string button_reset {
            get {
                return ResourceManager.GetString("button_reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сбросить уровень мобов.
        /// </summary>
        public static string button_reset_tool {
            get {
                return ResourceManager.GetString("button_reset_tool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на дроп / споил npc.
        /// </summary>
        public static string button_show {
            get {
                return ResourceManager.GetString("button_show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Скрыть\Показать панель дополнительных кнопок.
        /// </summary>
        public static string button_tooltip {
            get {
                return ResourceManager.GetString("button_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тип мобов:.
        /// </summary>
        public static string combo_npc {
            get {
                return ResourceManager.GetString("combo_npc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подбор по уязвимостям:.
        /// </summary>
        public static string combo_vulnerability {
            get {
                return ResourceManager.GetString("combo_vulnerability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Уровень.
        /// </summary>
        public static string details_lvl {
            get {
                return ResourceManager.GetString("details_lvl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Карта.
        /// </summary>
        public static string details_map {
            get {
                return ResourceManager.GetString("details_map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Скилы.
        /// </summary>
        public static string details_skils {
            get {
                return ResourceManager.GetString("details_skils", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дроп.
        /// </summary>
        public static string drop_box_fds {
            get {
                return ResourceManager.GetString("drop_box_fds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Шанс.
        /// </summary>
        public static string drop_chance {
            get {
                return ResourceManager.GetString("drop_chance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название.
        /// </summary>
        public static string drop_name {
            get {
                return ResourceManager.GetString("drop_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тип.
        /// </summary>
        public static string drop_tip {
            get {
                return ResourceManager.GetString("drop_tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вид.
        /// </summary>
        public static string drop_vid {
            get {
                return ResourceManager.GetString("drop_vid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hp 1х.
        /// </summary>
        public static string DropDownListReita_1 {
            get {
                return ResourceManager.GetString("DropDownListReita_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1/2 Hp.
        /// </summary>
        public static string DropDownListReita_1_2 {
            get {
                return ResourceManager.GetString("DropDownListReita_1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1/4 Hp.
        /// </summary>
        public static string DropDownListReita_1_4 {
            get {
                return ResourceManager.GetString("DropDownListReita_1_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hp увеличены (2х).
        /// </summary>
        public static string DropDownListReita_2x {
            get {
                return ResourceManager.GetString("DropDownListReita_2x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hp увеличены (3х).
        /// </summary>
        public static string DropDownListReita_3x {
            get {
                return ResourceManager.GetString("DropDownListReita_3x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hp увеличены (4х).
        /// </summary>
        public static string DropDownListReita_4x {
            get {
                return ResourceManager.GetString("DropDownListReita_4x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hp увеличены (5х).
        /// </summary>
        public static string DropDownListReita_5x {
            get {
                return ResourceManager.GetString("DropDownListReita_5x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hp увеличены (6х и выше).
        /// </summary>
        public static string DropDownListReita_6x_ {
            get {
                return ResourceManager.GetString("DropDownListReita_6x_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Все.
        /// </summary>
        public static string DropDownListReita_all {
            get {
                return ResourceManager.GetString("DropDownListReita_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка! Npc не найден.
        /// </summary>
        public static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Уровень.
        /// </summary>
        public static string fd_npc_lvl {
            get {
                return ResourceManager.GetString("fd_npc_lvl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Рейты.
        /// </summary>
        public static string fd_npc_raites {
            get {
                return ResourceManager.GetString("fd_npc_raites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Охрана.
        /// </summary>
        public static string fds_minion {
            get {
                return ResourceManager.GetString("fds_minion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Квесты где встречается нпц.
        /// </summary>
        public static string fds_quest {
            get {
                return ResourceManager.GetString("fds_quest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Гранд РБ.
        /// </summary>
        public static string grand_rb {
            get {
                return ResourceManager.GetString("grand_rb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Список мобов.
        /// </summary>
        public static string info_box_fds {
            get {
                return ResourceManager.GetString("info_box_fds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подробная информация.
        /// </summary>
        public static string info_details {
            get {
                return ResourceManager.GetString("info_details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ур..
        /// </summary>
        public static string info_lvl {
            get {
                return ResourceManager.GetString("info_lvl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Карта.
        /// </summary>
        public static string info_map {
            get {
                return ResourceManager.GetString("info_map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название.
        /// </summary>
        public static string info_name {
            get {
                return ResourceManager.GetString("info_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на English information.
        /// </summary>
        public static string localiz_en {
            get {
                return ResourceManager.GetString("localiz_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Язык инфы.
        /// </summary>
        public static string localiz_fds {
            get {
                return ResourceManager.GetString("localiz_fds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Русский язык инфы.
        /// </summary>
        public static string localiz_ru {
            get {
                return ResourceManager.GetString("localiz_ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кол-во.
        /// </summary>
        public static string minion_count {
            get {
                return ResourceManager.GetString("minion_count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя.
        /// </summary>
        public static string minion_name {
            get {
                return ResourceManager.GetString("minion_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Мобы.
        /// </summary>
        public static string mobs {
            get {
                return ResourceManager.GetString("mobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Npc.
        /// </summary>
        public static string npc {
            get {
                return ResourceManager.GetString("npc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Рейд босс.
        /// </summary>
        public static string rb {
            get {
                return ResourceManager.GetString("rb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поиск.
        /// </summary>
        public static string search_fds {
            get {
                return ResourceManager.GetString("search_fds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите имя NPC для поиска (русское или английское)..
        /// </summary>
        public static string search_span {
            get {
                return ResourceManager.GetString("search_span", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Споил.
        /// </summary>
        public static string spoil_box_fds {
            get {
                return ResourceManager.GetString("spoil_box_fds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тупое.
        /// </summary>
        public static string vb_blunt {
            get {
                return ResourceManager.GetString("vb_blunt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Лук.
        /// </summary>
        public static string vb_bow {
            get {
                return ResourceManager.GetString("vb_bow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дагер.
        /// </summary>
        public static string vb_dager {
            get {
                return ResourceManager.GetString("vb_dager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тьма.
        /// </summary>
        public static string vb_darc {
            get {
                return ResourceManager.GetString("vb_darc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дуал.
        /// </summary>
        public static string vb_dual {
            get {
                return ResourceManager.GetString("vb_dual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Земля.
        /// </summary>
        public static string vb_earth {
            get {
                return ResourceManager.GetString("vb_earth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Огонь.
        /// </summary>
        public static string vb_faer {
            get {
                return ResourceManager.GetString("vb_faer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Свет.
        /// </summary>
        public static string vb_holy {
            get {
                return ResourceManager.GetString("vb_holy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кастет.
        /// </summary>
        public static string vb_kastet {
            get {
                return ResourceManager.GetString("vb_kastet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Копьё.
        /// </summary>
        public static string vb_spear {
            get {
                return ResourceManager.GetString("vb_spear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Мечь.
        /// </summary>
        public static string vb_sword {
            get {
                return ResourceManager.GetString("vb_sword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вода.
        /// </summary>
        public static string vb_water {
            get {
                return ResourceManager.GetString("vb_water", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ветер.
        /// </summary>
        public static string vb_wind {
            get {
                return ResourceManager.GetString("vb_wind", resourceCulture);
            }
        }
    }
}
