//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18034
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Informer.Resources.Views {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Skils {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Skils() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Informer.Resources.Views.Skils", typeof(Skils).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Скилы профессии.
        /// </summary>
        public static string fd_clas_skils {
            get {
                return ResourceManager.GetString("fd_clas_skils", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Классы.
        /// </summary>
        public static string fd_class {
            get {
                return ResourceManager.GetString("fd_class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Уровни улучшения профессии.
        /// </summary>
        public static string fd_lvl_class {
            get {
                return ResourceManager.GetString("fd_lvl_class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Профессии.
        /// </summary>
        public static string fd_prof {
            get {
                return ResourceManager.GetString("fd_prof", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тип и уровень  заточки скилов.
        /// </summary>
        public static string fd_tochka {
            get {
                return ResourceManager.GetString("fd_tochka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Описание.
        /// </summary>
        public static string grid_add1_detail {
            get {
                return ResourceManager.GetString("grid_add1_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подробное описание.
        /// </summary>
        public static string grid_desc_detail {
            get {
                return ResourceManager.GetString("grid_desc_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Уровень и тип.
        /// </summary>
        public static string grid_lvl_detail {
            get {
                return ResourceManager.GetString("grid_lvl_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя.
        /// </summary>
        public static string grid_name {
            get {
                return ResourceManager.GetString("grid_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тип.
        /// </summary>
        public static string grid_tip {
            get {
                return ResourceManager.GetString("grid_tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Описание:.
        /// </summary>
        public static string th_desc {
            get {
                return ResourceManager.GetString("th_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тип:.
        /// </summary>
        public static string th_tip {
            get {
                return ResourceManager.GetString("th_tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Темный эльф.
        /// </summary>
        public static string tool_darc_elf {
            get {
                return ResourceManager.GetString("tool_darc_elf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Гном.
        /// </summary>
        public static string tool_dvarf {
            get {
                return ResourceManager.GetString("tool_dvarf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Эльф.
        /// </summary>
        public static string tool_elf {
            get {
                return ResourceManager.GetString("tool_elf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Человек.
        /// </summary>
        public static string tool_human {
            get {
                return ResourceManager.GetString("tool_human", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Камаел.
        /// </summary>
        public static string tool_kamael {
            get {
                return ResourceManager.GetString("tool_kamael", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Орк.
        /// </summary>
        public static string tool_orc {
            get {
                return ResourceManager.GetString("tool_orc", resourceCulture);
            }
        }
    }
}
