//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Informer.Areas.hf.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class class_list
    {
        public string class_name { get; set; }
        public int class_id { get; set; }
        public int class_parent_id { get; set; }
        public int class_max_prof { get; set; }
    }
}
