//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Informer.Areas.hf.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class high_five_4lUtkeEntities : DbContext
    {
        public high_five_4lUtkeEntities()
            : base("name=high_five_4lUtkeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<class_list> class_list { get; set; }
        public DbSet<class_race> class_race { get; set; }
        public DbSet<class_templates> class_templates { get; set; }
        public DbSet<item_desc> item_desc { get; set; }
        public DbSet<item_grp> item_grp { get; set; }
        public DbSet<item_name> item_name { get; set; }
        public DbSet<item_recipe> item_recipe { get; set; }
        public DbSet<item_recipe_ingr> item_recipe_ingr { get; set; }
        public DbSet<item_seeds> item_seeds { get; set; }
        public DbSet<item_set> item_set { get; set; }
        public DbSet<multisell_id> multisell_id { get; set; }
        public DbSet<multisell_shopids> multisell_shopids { get; set; }
        public DbSet<npc_desc_rb> npc_desc_rb { get; set; }
        public DbSet<npc_drop> npc_drop { get; set; }
        public DbSet<npc_grp> npc_grp { get; set; }
        public DbSet<npc_name> npc_name { get; set; }
        public DbSet<npc_rb_minion> npc_rb_minion { get; set; }
        public DbSet<npc_skilss> npc_skilss { get; set; }
        public DbSet<npc_spawn> npc_spawn { get; set; }
        public DbSet<quest_desc> quest_desc { get; set; }
        public DbSet<quest_full> quest_full { get; set; }
        public DbSet<quest_grp> quest_grp { get; set; }
        public DbSet<quest_items> quest_items { get; set; }
        public DbSet<quest_items_get> quest_items_get { get; set; }
        public DbSet<quest_name> quest_name { get; set; }
        public DbSet<quest_npc> quest_npc { get; set; }
        public DbSet<quest_npc_target> quest_npc_target { get; set; }
        public DbSet<skill_grp> skill_grp { get; set; }
        public DbSet<skils_desc_en> skils_desc_en { get; set; }
        public DbSet<skils_desc_ru> skils_desc_ru { get; set; }
        public DbSet<skils_oper_name> skils_oper_name { get; set; }
        public DbSet<skils_tree> skils_tree { get; set; }
    }
}
