//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Informer.Areas.hf.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class item_grp
    {
        public int item_id { get; set; }
        public int item_tag { get; set; }
        public int item_tip { get; set; }
        public int item_slot { get; set; }
        public int item_cry_tip { get; set; }
        public int item_cry_count { get; set; }
        public int item_weight { get; set; }
        public int item_price { get; set; }
        public int item_mdef { get; set; }
        public int item_pdef { get; set; }
        public int item_patt { get; set; }
        public int item_matt { get; set; }
        public int item_speed_atc { get; set; }
        public double item_crit_atc { get; set; }
        public int item_ss_count { get; set; }
        public int item_sps_count { get; set; }
        public int item_mp_consume { get; set; }
        public int item_mp_bonus { get; set; }
        public double item_accuracy { get; set; }
        public string item_img { get; set; }
        public int item_tradeable { get; set; }
        public int item_dropable { get; set; }
        public int item_crafr { get; set; }
        public int item_hero { get; set; }
    }
}
