//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Informer.Areas.hf.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class item_seeds
    {
        public int sed_castle_id { get; set; }
        public int sed_crop_id { get; set; }
        public int sed_seeds_id { get; set; }
        public int sed_mature_id { get; set; }
        public int sed_reward1_id { get; set; }
        public int sed_reward2_id { get; set; }
        public int sed_alternative { get; set; }
        public int sed_level { get; set; }
        public int sed_limit_seed { get; set; }
        public int sed_limit_crops { get; set; }
    }
}
