//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Informer.Areas.hf.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class item_recipe
    {
        public int rec_id_mk { get; set; }
        public int rec_tip_mk { get; set; }
        public int rec_id_recipe { get; set; }
        public int rec_level_recipe { get; set; }
        public int rec_id_item { get; set; }
        public int rec_item_count { get; set; }
        public int rec_mp_cost { get; set; }
        public int rec_success_rate { get; set; }
        public string rec_ingredient_id { get; set; }
        public string rec_ingredient_count { get; set; }
    }
}
