//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Informer.Areas.hf.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class item_set
    {
        public int set_id { get; set; }
        public int set_option { get; set; }
        public string set_structure { get; set; }
        public string set_tip_img { get; set; }
        public string set_name_img { get; set; }
        public string set_bonus_desc_ru { get; set; }
        public string set_extra_desc_ru { get; set; }
        public string set_enchant_desc_ru { get; set; }
        public string set_bonus_desc_en { get; set; }
        public string set_extra_desc_en { get; set; }
        public string set_enchant_desc_en { get; set; }
    }
}
