//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Informer.Areas.hf.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class npc_rb_minion
    {
        public int npc_id_rb { get; set; }
        public int npc_id_minion { get; set; }
        public int npc_minion_count { get; set; }
    }
}
