//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Informer.Areas.hf.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class npc_grp
    {
        public int npc_id { get; set; }
        public int npc_class { get; set; }
        public string npc_img { get; set; }
        public int npc_level { get; set; }
        public int npc_hp { get; set; }
        public int npc_exp { get; set; }
        public int npc_sp { get; set; }
        public int npc_reit { get; set; }
        public int npc_spawn { get; set; }
    }
}
