//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Informer.Areas.hf.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class npc_drop
    {
        public int npc_id { get; set; }
        public int category { get; set; }
        public int npc_item_id { get; set; }
        public int npc_min { get; set; }
        public int npc_max { get; set; }
        public float npc_chance { get; set; }
    }
}
