//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Informer.Areas.hf.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class quest_items_get
    {
        public int quest_id { get; set; }
        public int quest_tag { get; set; }
        public int quest_prog { get; set; }
        public int quest_items_id { get; set; }
        public int quest_items_count { get; set; }
    }
}
