//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Informer.Areas.hf.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class quest_grp
    {
        public int quest_id { get; set; }
        public int quest_lvl_min { get; set; }
        public int quest_lvl_max { get; set; }
        public int quest_type { get; set; }
        public int quest_clan_pet { get; set; }
        public int quest_complete { get; set; }
        public int quest_area_id { get; set; }
        public int quest_npc_id { get; set; }
        public int quest_npc_x { get; set; }
        public int quest_npc_y { get; set; }
    }
}
