//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Informer.Areas.hf.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class quest_full
    {
        public int quest_id { get; set; }
        public string quest_en { get; set; }
        public string quest_ru { get; set; }
        public string quest_html { get; set; }
        public int quest_end { get; set; }
        public string quest_name_editor { get; set; }
    }
}
