//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Informer.Areas.hf.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class quest_desc
    {
        public int quest_id { get; set; }
        public int quest_prog { get; set; }
        public string quest_prog_name { get; set; }
        public string quest_desc1 { get; set; }
        public int quest_x { get; set; }
        public int quest_y { get; set; }
    }
}
