//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Informer.Areas.hf.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class quest_name
    {
        public int quest_id { get; set; }
        public string quest_names { get; set; }
        public string quest_restricions { get; set; }
        public string quest_short_desc { get; set; }
        public string quest_names_en { get; set; }
        public string quest_restricions_en { get; set; }
        public string quest_short_desc_en { get; set; }
    }
}
