//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Informer.Areas.hf.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class skill_grp
    {
        public int skil_id { get; set; }
        public int skil_lvl { get; set; }
        public int skil_oper_type { get; set; }
        public string skil_img { get; set; }
        public string skil_name_ru { get; set; }
        public string skil_name_en { get; set; }
    }
}
