//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Informer.Areas.hf.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class skils_desc_en
    {
        public int skil_id { get; set; }
        public int skil_lvl { get; set; }
        public string skil_desc { get; set; }
        public string skil_desc_add1 { get; set; }
        public string skil_desc_add2 { get; set; }
    }
}
