//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Informer.Areas.hf.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class skils_tree
    {
        public int skil_class_id { get; set; }
        public int skil_id { get; set; }
        public int skil_lvl { get; set; }
        public int skil_cost { get; set; }
        public int skil_min_level { get; set; }
        public int skil_item_id { get; set; }
        public int skiol_item_count { get; set; }
        public int skil_clicked { get; set; }
    }
}
