//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.17929
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // класс с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить элемент, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте проект Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EditorLocalization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EditorLocalization() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, используемый этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.EditorLocalization", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Переопределяет свойство CurrentUICulture текущего потока для всех
        ///   подстановки ресурсов с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Bold.
        /// </summary>
        internal static string Bold {
            get {
                return ResourceManager.GetString("Bold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Insert hyperlink.
        /// </summary>
        internal static string CreateLink {
            get {
                return ResourceManager.GetString("CreateLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Are you sure you want to delete {0}?.
        /// </summary>
        internal static string DeleteFile {
            get {
                return ResourceManager.GetString("DeleteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как A directory with this name was not found..
        /// </summary>
        internal static string DirectoryNotFound {
            get {
                return ResourceManager.GetString("DirectoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Empty Folder.
        /// </summary>
        internal static string EmptyFolder {
            get {
                return ResourceManager.GetString("EmptyFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Select font family.
        /// </summary>
        internal static string FontName {
            get {
                return ResourceManager.GetString("FontName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как (inherited font).
        /// </summary>
        internal static string FontNameInherit {
            get {
                return ResourceManager.GetString("FontNameInherit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Select font size.
        /// </summary>
        internal static string FontSize {
            get {
                return ResourceManager.GetString("FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как (inherited size).
        /// </summary>
        internal static string FontSizeInherit {
            get {
                return ResourceManager.GetString("FontSizeInherit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Select block type.
        /// </summary>
        internal static string FormatBlock {
            get {
                return ResourceManager.GetString("FormatBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Indent.
        /// </summary>
        internal static string Indent {
            get {
                return ResourceManager.GetString("Indent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Insert.
        /// </summary>
        internal static string Insert {
            get {
                return ResourceManager.GetString("Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Insert HTML.
        /// </summary>
        internal static string InsertHtml {
            get {
                return ResourceManager.GetString("InsertHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Insert image.
        /// </summary>
        internal static string InsertImage {
            get {
                return ResourceManager.GetString("InsertImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Insert ordered list.
        /// </summary>
        internal static string InsertOrderedList {
            get {
                return ResourceManager.GetString("InsertOrderedList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Insert unordered list.
        /// </summary>
        internal static string InsertUnorderedList {
            get {
                return ResourceManager.GetString("InsertUnorderedList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как The selected file {0} is not valid. Supported file types are {1}..
        /// </summary>
        internal static string InvalidFileType {
            get {
                return ResourceManager.GetString("InvalidFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Italic.
        /// </summary>
        internal static string Italic {
            get {
                return ResourceManager.GetString("Italic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Center text.
        /// </summary>
        internal static string JustifyCenter {
            get {
                return ResourceManager.GetString("JustifyCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Justify.
        /// </summary>
        internal static string JustifyFull {
            get {
                return ResourceManager.GetString("JustifyFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Align text left.
        /// </summary>
        internal static string JustifyLeft {
            get {
                return ResourceManager.GetString("JustifyLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Align text right.
        /// </summary>
        internal static string JustifyRight {
            get {
                return ResourceManager.GetString("JustifyRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Open link in new window.
        /// </summary>
        internal static string OpenInNewWindow {
            get {
                return ResourceManager.GetString("OpenInNewWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как or.
        /// </summary>
        internal static string Or {
            get {
                return ResourceManager.GetString("Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Arrange by:.
        /// </summary>
        internal static string OrderBy {
            get {
                return ResourceManager.GetString("OrderBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Name.
        /// </summary>
        internal static string OrderByName {
            get {
                return ResourceManager.GetString("OrderByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Size.
        /// </summary>
        internal static string OrderBySize {
            get {
                return ResourceManager.GetString("OrderBySize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Outdent.
        /// </summary>
        internal static string Outdent {
            get {
                return ResourceManager.GetString("Outdent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как A file with name {0} already exists in the current directory. Do you want to overwrite it?.
        /// </summary>
        internal static string OverwriteFile {
            get {
                return ResourceManager.GetString("OverwriteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Strikethrough.
        /// </summary>
        internal static string Strikethrough {
            get {
                return ResourceManager.GetString("Strikethrough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Styles.
        /// </summary>
        internal static string Style {
            get {
                return ResourceManager.GetString("Style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Tooltip.
        /// </summary>
        internal static string Tooltip {
            get {
                return ResourceManager.GetString("Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Underline.
        /// </summary>
        internal static string Underline {
            get {
                return ResourceManager.GetString("Underline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Remove hyperlink.
        /// </summary>
        internal static string Unlink {
            get {
                return ResourceManager.GetString("Unlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Upload.
        /// </summary>
        internal static string UploadFile {
            get {
                return ResourceManager.GetString("UploadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Web address.
        /// </summary>
        internal static string WebAddress {
            get {
                return ResourceManager.GetString("WebAddress", resourceCulture);
            }
        }
    }
}
