//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Informer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class home_news
    {
        public int id { get; set; }
        public string title { get; set; }
        public int rating { get; set; }
        public Nullable<System.DateTime> data { get; set; }
        public int autor_id { get; set; }
        public string preview { get; set; }
        public string content { get; set; }
        public int category_id { get; set; }
        public int adm_edit { get; set; }
        public string description { get; set; }
    }
}
