//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Informer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lsMessages
    {
        public int msg_id { get; set; }
        public int from_id { get; set; }
        public int to_id { get; set; }
        public string subj { get; set; }
        public System.DateTime date { get; set; }
        public int status { get; set; }
        public string title { get; set; }
    }
}
