//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Informer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_ignore
    {
        public int userId { get; set; }
        public int userIdIgnor { get; set; }
        public int id { get; set; }
    }
}
